sudo: false

language: cpp

addons:
    apt:
        sources:
            # - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            # - clang-3.7
            - gcc-5
            - g++-5
            - libboost-iostreams1.55-dev
            - zlib

compiler:
    - gcc
    # - clang

notifications:
  email:
    on_success: never
    on_failure: always

before_script:
    - "mkdir ${TRAVIS_BUILD_DIR}/build-{debug,opt}"

before_install:
    - bash travis/install_zmqpp.sh

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    # - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script: ./travis/travis_build.sh

